#ifndef TRANSACTIONS_SRC_UTILS_RED_BLACK_TREE_RB_TREE_H_
#define TRANSACTIONS_SRC_UTILS_RED_BLACK_TREE_RB_TREE_H_

namespace s21 {

class RBTree {};

}  // namespace s21

#endif  // TRANSACTIONS_SRC_UTILS_RED_BLACK_TREE_RB_TREE_H_
