#ifndef TRANSACTIONS_SRC_INCLUDE_SELF_BALANCING_BINARY_SEARCH_TREE_H_
#define TRANSACTIONS_SRC_INCLUDE_SELF_BALANCING_BINARY_SEARCH_TREE_H_

namespace s21 {

class SelfBalancingBinarySearchTree {

};

}  // namespace s21

#endif  // TRANSACTIONS_SRC_INCLUDE_SELF_BALANCING_BINARY_SEARCH_TREE_H_
